spring.application.name=demoBack
// filepath: /path/to/src/main/resources/application.properties
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=http://synet.riberadeltajo.es/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=profile,email
server.port=8080
spring.jackson.serialization.indent_output=true

# Conexión base de datos
spring.data.mongodb.uri=mongodb://mongo:27017/equiposynet_db
spring.data.mongodb.database=equiposynet_db

#Cabeceras de nginx
server.forward-headers-strategy=framework

# CORS (si el frontend está en otro origen)
spring.web.cors.allowed-origins=http://localhost:3000
