spring.application.name=demoBack

server.port=8080
spring.jackson.serialization.indent_output=true

# MongoDB
spring.data.mongodb.uri=mongodb://mongo:27017/clinica

# OAuth Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

server.forward-headers-strategy=native
